import fs from 'node:fs/promises';
import path from 'node:path';

/**
 * Emit a Jupyter Book project from a list of Markdown chapter paths (copied into outDir).
 * When `thebe` is true (AI Dialogic), adds launch buttons and Binder repo for in-browser execution.
 * @param {object} o
 * @param {string} o.title
 * @param {{ path: string, title?: string }[]} o.chapters — paths relative to myst project (e.g. `lessons/week-01.md`)
 * @param {string} o.mystProjectDir
 * @param {string} o.outDir — Jupyter Book root (contains _config.yml, _toc.yml, content/)
 * @param {string} [o.variantKey]
 * @param {boolean} [o.thebe] — Enable Thebe / live kernels in built HTML
 * @param {string} [o.binderRepo] — e.g. `aimacode/aima-python`
 * @param {string} [o.binderRef] — git ref for Binder
 */
export async function buildJupyterBookProject(o) {
  const {
    title,
    chapters,
    mystProjectDir,
    outDir,
    thebe = false,
    binderRepo = 'aimacode/aima-python',
    binderRef = 'master',
  } = o;
  const contentDir = path.join(outDir, 'content');
  await fs.mkdir(contentDir, { recursive: true });

  const toc = {
    format: 'jb-book',
    root: 'intro',
    chapters: [],
  };

  const rootMd = path.join(contentDir, 'intro.md');
  await fs.writeFile(
    rootMd,
    `# ${title}\n\nGenerated by myst-imscc from MyST sources.\n`,
    'utf8'
  );

  for (let i = 0; i < chapters.length; i++) {
    const ch = chapters[i];
    const base = path.basename(ch.path, path.extname(ch.path));
    const safe = `${String(i + 1).padStart(2, '0')}-${base.replace(/[^a-z0-9-_]/gi, '-')}`;
    const destName = `${safe}.md`;
    const srcAbs = path.join(mystProjectDir, ch.path);
    const body = await fs.readFile(srcAbs, 'utf8');
    await fs.writeFile(path.join(contentDir, destName), body, 'utf8');
    toc.chapters.push({ file: destName.replace(/\.md$/, ''), title: ch.title ?? base });
  }

  const repoUrl = `https://github.com/${binderRepo}`;
  const thebeBlock =
    thebe
      ? `
repository:
  url: ${JSON.stringify(repoUrl)}
html:
  use_thebe_lite: true
launch_buttons:
  thebe: true
  binderhub_url: https://mybinder.org
`
      : '';

  const configYml = `title: ${JSON.stringify(title)}
author: Inquiry Institute
execute:
  execute_notebooks: off
parse:
  myst_enable_extensions: true
${thebeBlock}`;

  const tocLines = ['format: jb-book', 'root: intro', 'chapters:'];
  for (const ch of toc.chapters) {
    tocLines.push(`  - file: ${ch.file}`);
    if (ch.title) tocLines.push(`    title: ${JSON.stringify(ch.title)}`);
  }
  const tocYml = tocLines.join('\n') + '\n';

  await fs.writeFile(path.join(outDir, '_config.yml'), configYml, 'utf8');
  await fs.writeFile(path.join(outDir, '_toc.yml'), tocYml, 'utf8');
}
